[package]
name = "gcn-fonts-macro"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
syn = "0.14.7"
worker = { path = "../worker" }

[lib]
proc-macro = true
